# Generated by Django 5.1.5 on 2025-05-02 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_arts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Arts'},
        ),
        migrations.AddField(
            model_name='arts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
