# Generated by Django 5.1.5 on 2025-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_arts_options_arts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='team_profile/')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('arrangement', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['arrangement'],
            },
        ),
    ]
