# Generated by Django 5.1.5 on 2025-05-24 12:35

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='OurImpact/')),
                ('name', models.CharField(max_length=255)),
                ('story', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Our Impacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
