# Generated by Django 5.1.5 on 2025-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_ourimpact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourimpact',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
