# Generated by Django 5.1.5 on 2025-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_ourimpact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourimpact',
            name='story_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
